[package]
name = "rust_engine"
version = "0.0.1"
authors = ["danielvisser <danielvisser10@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version="0.7.3", features=["small_rng"]}
